FROM infotrainingdev/gcc15-cmake410-vcpkg-nolibs:latest

WORKDIR /root

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>